### ISSUE TITLE
Library does not react to state of datastore

### ISSUE THREAD

**Issue by mtotschnig** [burnoo/compose-remember-preference#3]
Currently the library sets the value from the DataStore only on first load, it then only refers to its own state.
I think this is bad design, because the edit of the new value could fail, and the consumer should not be made believe that the operation succeeded.
While this might seem only of academic interest (and one might argue, that for certain use cases, you might want to use the new value even if it does not get persisted), there is a use case where it makes a difference:
Imagine that the keyName is dynamic, for example, the UI has different modes, and each mode is supposed to have its own value for a certain component on the screen. In the current design, the library fails to reload the value when the mode/keyName changes.

**Comment by burnoo** [comment]
I've open two PRs: https://github.com/burnoo/compose-remember-preference/pull/4 & https://github.com/burnoo/compose-remember-preference/pull/5 that are improving things you mentioned.

Feel free to do a Code Review or ask more questions

**Comment by mtotschnig** [comment]
Thanks for reacting quickly to my concern. Both PRs look good to me.

**Comment by burnoo** [comment]
I've included those changes in the [new release](https://github.com/burnoo/compose-remember-preference/releases/tag/1.0.0) 🎉
